apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-kafka-postgres
  labels:
    app: spark-kafka-postgres
    version: v1.1
spec:
  serviceName: spark-kafka-postgres-headless-svc
  replicas: 1
  selector:
    matchLabels:
      app: spark-kafka-postgres
      version: v1.1
  template:
    metadata:
      labels:
        app: spark-kafka-postgres
        version: v1.1
    spec:
      serviceAccountName: spark
      containers:
        - name: kafka-postgres
          image: lockhart07/ttt_spark_lab5:v3.0
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_URL
              value: "jdbc:postgresql://postgres-svc:5432/mydatabase"
            - name: POSTGRES_PASSWORD
              value: "root"
            - name: POSTGRES_USERNAME
              value: "root"
            - name: KAFKA_BOOTSTRAP_SERVER
              value: "my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
            - name: KAFKA_READ_TOPIC
              value: "wine"
            - name: SPARK_KUBERNETES_CONTAINER_IMAGE
              value: "lockhart07/ttt_spark_lab5:v3.0"
            - name: SPARK_KUBERNETES_DRIVER_MASTER
              value: "k8s://http://127.0.0.1:6443"
            - name: SPARK_KUBERNETES_DRIVER_POD_NAME
              value: "spark-driver"
            - name: SPARK_KUBERNETES_AUTHENTICATE_DRIVER_SERVICE_ACCOUNT_NAME
              value: "spark"
            - name: SPARK_KUBERNETES_EXECUTOR_PODNAMEPREFIX
              value: "spark-executor"
            - name: SPARK_DRIVER_HOST
              value: "spark-kafka-postgres-headless-svc"
            - name: SPARK_DRIVER_PORT
              value: "8081"
            - name: SPARK_EXECUTOR_INSTANCES
              value: "2"
            - name: SPARK_EXECUTOR_CORES
              value: "1"
            - name: SPARK_EXECUTOR_MEMORY
              value: 512M
