import os


POSTGRES_URL = os.environ["POSTGRES_URL"]
POSTGRES_PASSWORD = os.environ["POSTGRES_PASSWORD"]
POSTGRES_USERNAME = os.environ["POSTGRES_USERNAME"]


KAFKA_BOOTSTRAP_SERVER = os.environ["KAFKA_BOOTSTRAP_SERVER"]
KAFKA_READ_TOPIC = os.environ["KAFKA_READ_TOPIC"]



SPARK_KUBERNETES_CONTAINER_IMAGE = os.environ['SPARK_KUBERNETES_CONTAINER_IMAGE']
SPARK_KUBERNETES_DRIVER_MASTER = os.environ['SPARK_KUBERNETES_DRIVER_MASTER']
SPARK_KUBERNETES_DRIVER_POD_NAME = os.environ['SPARK_KUBERNETES_DRIVER_POD_NAME']
SPARK_KUBERNETES_AUTHENTICATE_DRIVER_SERVICE_ACCOUNT_NAME = os.environ['SPARK_KUBERNETES_AUTHENTICATE_DRIVER_SERVICE_ACCOUNT_NAME']
SPARK_KUBERNETES_EXECUTOR_PODNAMEPREFIX = os.environ['SPARK_KUBERNETES_EXECUTOR_PODNAMEPREFIX']
SPARK_DRIVER_HOST = os.environ['SPARK_DRIVER_HOST']
SPARK_DRIVER_PORT = os.environ['SPARK_DRIVER_PORT']
SPARK_EXECUTOR_INSTANCES = os.environ['SPARK_EXECUTOR_INSTANCES']
SPARK_EXECUTOR_CORES = os.environ['SPARK_EXECUTOR_CORES']
SPARK_EXECUTOR_MEMORY = os.environ['SPARK_EXECUTOR_MEMORY']
