apiVersion: v1
kind: Service
metadata:
  name: spark-kafka-postgres-headless-svc
spec:
  selector:
    app: spark-kafka-postgres
  ports:
    - name: spark-kafka-postgres
      port: 8081
      targetPort: 8081
  clusterIP: None
  type: ClusterIP
